### ISSUE TITLE
Change exit code

### ISSUE THREAD

**Issue by fpetr** [jonasbb/podman-gitlab-runner#24]
Hi, I am using this executor but it seems to be impossible to change behaviour of exit code. The problem I am facing is that when I execute som .sh script on runner which should exit with status code 22 the final status code is always 1 anyway.

In this case i am not able to use _allow_failure_ in my .gitlab-ci.yml file.

```yaml
  allow_failure:
    exit_codes:
      - 22
```
I found that there is variable "$BUILD_FAILURE_EXIT_CODE" in run.sh script but where is this coming from ?

Is there any possibility to change this behaviour ?

Thank you very much.

**Comment by jonasbb** [comment]
Hi, this doesn't really seem related to this repository. If something inside your gitlab-ci.yml breaks, then it is likely not the fault of the custom executor, but of the gitlab runner.
The script exit codes are pre-defined and have to be used. They are described in the custom executor documentation https://docs.gitlab.com/runner/executors/custom.html.

If the code here is not working for you, it is probably best to switch to the officially podman support: https://docs.gitlab.com/runner/executors/docker.html#use-podman-to-run-docker-commands-beta
